#include "ruby.h"

#include <fcntl.h>
#include <sys/wait.h>

#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <netinet/udp.h>
#include <netdb.h>
#include <net/if.h>


#define DEF_CONST_INT(mod, v) rb_define_const(mod, #v, INT2NUM(v))

void um_define_net_constants(VALUE mod) {
  DEF_CONST_INT(mod, O_APPEND);
  DEF_CONST_INT(mod, O_CLOEXEC);
  DEF_CONST_INT(mod, O_CREAT);
  DEF_CONST_INT(mod, O_DIRECT);
  DEF_CONST_INT(mod, O_DIRECTORY);
  DEF_CONST_INT(mod, O_DSYNC);
  DEF_CONST_INT(mod, O_EXCL);
  DEF_CONST_INT(mod, O_NOCTTY);
  DEF_CONST_INT(mod, O_NOFOLLOW);
  DEF_CONST_INT(mod, O_PATH);
  DEF_CONST_INT(mod, O_RDONLY);
  DEF_CONST_INT(mod, O_RDWR);
  DEF_CONST_INT(mod, O_SYNC);
  DEF_CONST_INT(mod, O_TMPFILE);
  DEF_CONST_INT(mod, O_TRUNC);
  DEF_CONST_INT(mod, O_WRONLY);

  DEF_CONST_INT(mod, WNOHANG);
  DEF_CONST_INT(mod, WUNTRACED);
  DEF_CONST_INT(mod, WCONTINUED);
  DEF_CONST_INT(mod, WEXITED);
  DEF_CONST_INT(mod, WSTOPPED);
  DEF_CONST_INT(mod, WNOWAIT);

  DEF_CONST_INT(mod, SOCK_STREAM);
  DEF_CONST_INT(mod, SOCK_DGRAM);
  DEF_CONST_INT(mod, SOCK_RAW);
  DEF_CONST_INT(mod, SOCK_RDM);
  DEF_CONST_INT(mod, SOCK_SEQPACKET);
  DEF_CONST_INT(mod, SOCK_PACKET);
  DEF_CONST_INT(mod, SOCK_CLOEXEC);

  DEF_CONST_INT(mod, AF_UNSPEC);
  DEF_CONST_INT(mod, PF_UNSPEC);
  DEF_CONST_INT(mod, AF_INET);
  DEF_CONST_INT(mod, PF_INET);
  DEF_CONST_INT(mod, AF_INET6);
  DEF_CONST_INT(mod, PF_INET6);
  DEF_CONST_INT(mod, AF_UNIX);
  DEF_CONST_INT(mod, PF_UNIX);
  DEF_CONST_INT(mod, AF_LOCAL);
  DEF_CONST_INT(mod, PF_LOCAL);
  DEF_CONST_INT(mod, AF_ROUTE);
  DEF_CONST_INT(mod, PF_ROUTE);
  DEF_CONST_INT(mod, AF_MAX);
  DEF_CONST_INT(mod, PF_MAX);

  DEF_CONST_INT(mod, MSG_OOB);
  DEF_CONST_INT(mod, MSG_PEEK);
  DEF_CONST_INT(mod, MSG_DONTROUTE);
  DEF_CONST_INT(mod, MSG_WAITALL);
  DEF_CONST_INT(mod, MSG_DONTWAIT);
  DEF_CONST_INT(mod, MSG_MORE);

  DEF_CONST_INT(mod, SOL_SOCKET);
  DEF_CONST_INT(mod, SOL_IP);

  DEF_CONST_INT(mod, IPPROTO_IP);
  DEF_CONST_INT(mod, IPPROTO_ICMP);
  DEF_CONST_INT(mod, IPPROTO_IGMP);
  DEF_CONST_INT(mod, IPPROTO_TCP);
  DEF_CONST_INT(mod, IPPROTO_EGP);
  DEF_CONST_INT(mod, IPPROTO_PUP);
  DEF_CONST_INT(mod, IPPROTO_UDP);
  DEF_CONST_INT(mod, IPPROTO_IDP);
  DEF_CONST_INT(mod, IPPROTO_IPV6);
  DEF_CONST_INT(mod, IPPROTO_NONE);
  DEF_CONST_INT(mod, IPPROTO_ROUTING);
  DEF_CONST_INT(mod, IPPROTO_RAW);
  DEF_CONST_INT(mod, IPPROTO_MAX);

  DEF_CONST_INT(mod, INADDR_ANY);
  DEF_CONST_INT(mod, INADDR_BROADCAST);
  DEF_CONST_INT(mod, INADDR_LOOPBACK);
  DEF_CONST_INT(mod, INADDR_NONE);

  DEF_CONST_INT(mod, IP_OPTIONS);
  DEF_CONST_INT(mod, IP_HDRINCL);
  DEF_CONST_INT(mod, IP_TOS);
  DEF_CONST_INT(mod, IP_TTL);
  DEF_CONST_INT(mod, IP_RECVOPTS);
  DEF_CONST_INT(mod, IP_MINTTL);
  DEF_CONST_INT(mod, IP_RECVTTL);

  DEF_CONST_INT(mod, SO_DEBUG);
  DEF_CONST_INT(mod, SO_REUSEADDR);
  DEF_CONST_INT(mod, SO_REUSEPORT);
  DEF_CONST_INT(mod, SO_TYPE);
  DEF_CONST_INT(mod, SO_ERROR);
  DEF_CONST_INT(mod, SO_DONTROUTE);
  DEF_CONST_INT(mod, SO_BROADCAST);
  DEF_CONST_INT(mod, SO_SNDBUF);
  DEF_CONST_INT(mod, SO_RCVBUF);
  DEF_CONST_INT(mod, SO_SNDBUFFORCE);
  DEF_CONST_INT(mod, SO_RCVBUFFORCE);
  DEF_CONST_INT(mod, SO_KEEPALIVE);
  DEF_CONST_INT(mod, SO_OOBINLINE);
  DEF_CONST_INT(mod, SO_PRIORITY);
  DEF_CONST_INT(mod, SO_LINGER);
  DEF_CONST_INT(mod, SO_PASSCRED);
  DEF_CONST_INT(mod, SO_PEERCRED);
  DEF_CONST_INT(mod, SO_RCVLOWAT);
  DEF_CONST_INT(mod, SO_SNDLOWAT);
  DEF_CONST_INT(mod, SO_RCVTIMEO);
  DEF_CONST_INT(mod, SO_SNDTIMEO);
  DEF_CONST_INT(mod, SO_ACCEPTCONN);
  DEF_CONST_INT(mod, SO_PEERNAME);
  DEF_CONST_INT(mod, SO_TIMESTAMP);
  DEF_CONST_INT(mod, SO_MARK);
  DEF_CONST_INT(mod, SO_PROTOCOL);
  DEF_CONST_INT(mod, SO_DOMAIN);
  DEF_CONST_INT(mod, SO_PEEK_OFF);
  DEF_CONST_INT(mod, SO_BUSY_POLL);

  DEF_CONST_INT(mod, TCP_NODELAY);
  DEF_CONST_INT(mod, TCP_MAXSEG);
  DEF_CONST_INT(mod, TCP_CORK);
  DEF_CONST_INT(mod, TCP_DEFER_ACCEPT);
  DEF_CONST_INT(mod, TCP_INFO);
  DEF_CONST_INT(mod, TCP_KEEPCNT);
  DEF_CONST_INT(mod, TCP_KEEPIDLE);
  DEF_CONST_INT(mod, TCP_KEEPINTVL);
  DEF_CONST_INT(mod, TCP_LINGER2);
  DEF_CONST_INT(mod, TCP_MD5SIG);
  DEF_CONST_INT(mod, TCP_QUICKACK);
  DEF_CONST_INT(mod, TCP_SYNCNT);
  DEF_CONST_INT(mod, TCP_WINDOW_CLAMP);
  DEF_CONST_INT(mod, TCP_FASTOPEN);
  DEF_CONST_INT(mod, TCP_CONGESTION);
  DEF_CONST_INT(mod, TCP_COOKIE_TRANSACTIONS);
  DEF_CONST_INT(mod, TCP_QUEUE_SEQ);
  DEF_CONST_INT(mod, TCP_REPAIR);
  DEF_CONST_INT(mod, TCP_REPAIR_OPTIONS);
  DEF_CONST_INT(mod, TCP_REPAIR_QUEUE);
  DEF_CONST_INT(mod, TCP_THIN_LINEAR_TIMEOUTS);
  DEF_CONST_INT(mod, TCP_TIMESTAMP);
  DEF_CONST_INT(mod, TCP_USER_TIMEOUT);
  
  DEF_CONST_INT(mod, UDP_CORK);

  DEF_CONST_INT(mod, AI_PASSIVE);
  DEF_CONST_INT(mod, AI_CANONNAME);
  DEF_CONST_INT(mod, AI_NUMERICHOST);
  DEF_CONST_INT(mod, AI_NUMERICSERV);
  DEF_CONST_INT(mod, AI_ALL);
  DEF_CONST_INT(mod, AI_ADDRCONFIG);
  DEF_CONST_INT(mod, AI_V4MAPPED);
  
  DEF_CONST_INT(mod, NI_MAXHOST);
  DEF_CONST_INT(mod, NI_MAXSERV);
  DEF_CONST_INT(mod, NI_NOFQDN);
  DEF_CONST_INT(mod, NI_NUMERICHOST);
  DEF_CONST_INT(mod, NI_NAMEREQD);
  DEF_CONST_INT(mod, NI_NUMERICSERV);
  DEF_CONST_INT(mod, NI_DGRAM);
  
  DEF_CONST_INT(mod, SHUT_RD);
  DEF_CONST_INT(mod, SHUT_WR);
  DEF_CONST_INT(mod, SHUT_RDWR);

  DEF_CONST_INT(mod, IPV6_JOIN_GROUP);
  DEF_CONST_INT(mod, IPV6_LEAVE_GROUP);
  DEF_CONST_INT(mod, IPV6_MULTICAST_HOPS);
  DEF_CONST_INT(mod, IPV6_MULTICAST_IF);
  DEF_CONST_INT(mod, IPV6_MULTICAST_LOOP);
  DEF_CONST_INT(mod, IPV6_UNICAST_HOPS);
  DEF_CONST_INT(mod, IPV6_V6ONLY);
  DEF_CONST_INT(mod, IPV6_CHECKSUM);
  DEF_CONST_INT(mod, IPV6_DONTFRAG);
  DEF_CONST_INT(mod, IPV6_DSTOPTS);
  DEF_CONST_INT(mod, IPV6_HOPLIMIT);
  DEF_CONST_INT(mod, IPV6_HOPOPTS);
  DEF_CONST_INT(mod, IPV6_NEXTHOP);
  DEF_CONST_INT(mod, IPV6_PATHMTU);
  DEF_CONST_INT(mod, IPV6_PKTINFO);
  DEF_CONST_INT(mod, IPV6_RECVDSTOPTS);
  DEF_CONST_INT(mod, IPV6_RECVHOPLIMIT);
  DEF_CONST_INT(mod, IPV6_RECVHOPOPTS);
  DEF_CONST_INT(mod, IPV6_RECVPKTINFO);
  DEF_CONST_INT(mod, IPV6_RECVRTHDR);
  DEF_CONST_INT(mod, IPV6_RECVTCLASS);
  DEF_CONST_INT(mod, IPV6_RTHDR);
  DEF_CONST_INT(mod, IPV6_RTHDRDSTOPTS);
  DEF_CONST_INT(mod, IPV6_RTHDR_TYPE_0);
  DEF_CONST_INT(mod, IPV6_RECVPATHMTU);
  DEF_CONST_INT(mod, IPV6_TCLASS);

  DEF_CONST_INT(mod, INET_ADDRSTRLEN);
  DEF_CONST_INT(mod, INET6_ADDRSTRLEN);

  DEF_CONST_INT(mod, IF_NAMESIZE);

  DEF_CONST_INT(mod, SOMAXCONN);
}
